spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tasklib?useSSL=false
    username: root
    password: dfgIU987fmS
spring.jpa.hibernate.ddl-auto: create-drop