spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tasklib?useSSL=false
    username: root
    password: dfgIU987fmS
spring.jpa.hibernate.ddl-auto: create
spring.datasource.initialization-mode: always
spring.servlet.multipart.max-file-size: 1280KB
spring.servlet.multipart.max-request-size: 1280KB
spring.servlet.multipart.enabled: true
spring.servlet.multipart.location: ${java.io.tmpdir}